# Generated by Django 5.0.1 on 2024-01-10 22:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service', verbose_name='Фото')),
                ('image2', models.ImageField(upload_to='service/', verbose_name='Фото на дитальный просмотр')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание заголовка')),
                ('descriptions2', ckeditor.fields.RichTextField(verbose_name='Описание 2')),
                ('video', models.URLField(verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Лучшие услуги',
                'verbose_name_plural': 'Лучшие услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
    ]
