# Generated by Django 5.0.1 on 2024-01-10 23:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_recservice_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsService',
            fields=[
                ('image', models.ImageField(upload_to='service', verbose_name='Фото')),
                ('image2', models.ImageField(upload_to='service/', verbose_name='Фото на дитальный просмотр')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание заголовка')),
                ('descriptions2', ckeditor.fields.RichTextField(verbose_name='Описание 2')),
                ('video', models.URLField(verbose_name='Видео')),
                ('number', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_title', to='products.recservice')),
            ],
            options={
                'verbose_name': 'Лучшая услуга',
                'verbose_name_plural': 'Лучшие услуги',
                'unique_together': {('service', 'image', 'image2', 'title', 'descriptions', 'descriptions2', 'video', 'number')},
            },
        ),
    ]
