# Generated by Django 5.0.1 on 2024-01-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_bestservice_delete_settingsservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestservice',
            options={'verbose_name': 'Частые услуга', 'verbose_name_plural': 'Частые услуги'},
        ),
    ]
