# Generated by Django 5.0.1 on 2024-01-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_oftenservice_delete_bestservice_delete_recservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oftenservice',
            options={'verbose_name': 'Чатстый вопрос', 'verbose_name_plural': 'Чатсты вопросы'},
        ),
    ]
