# Generated by Django 5.0.1 on 2024-01-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_oftenservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oftenservice',
            options={'verbose_name': 'Частый вопрос', 'verbose_name_plural': 'Частые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '1) Услуги', 'verbose_name_plural': '1) Услуги'},
        ),
    ]
