# Generated by Django 5.0.1 on 2024-01-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_oftenservice_options_alter_service_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OftenService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
