# Generated by Django 5.0.1 on 2024-01-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_delete_telegramuser_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
