# Generated by Django 5.0.1 on 2024-01-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0006_delete_contact_delete_newsletter_delete_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Cообщение')),
            ],
            options={
                'verbose_name': 'Зопрос на Блоге',
                'verbose_name_plural': 'Зопросs на Блоге',
            },
        ),
    ]
