# Generated by Django 5.0.1 on 2024-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Cообщение')),
            ],
            options={
                'verbose_name': 'Зопрос о услуге',
                'verbose_name_plural': 'Зопросы на услуги',
            },
        ),
    ]
