# Generated by Django 5.0.1 on 2024-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default=1, max_length=255, verbose_name='страна'),
            preserve_default=False,
        ),
    ]
