# Generated by Django 5.0.1 on 2024-01-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcontact',
            options={'verbose_name': '1) Запрос на Блоге', 'verbose_name_plural': '1) Запросы на Блоге'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '4) Контакт', 'verbose_name_plural': '4) Контакты'},
        ),
        migrations.AlterModelOptions(
            name='servicecontact',
            options={'verbose_name': '2) Запрос о услуге', 'verbose_name_plural': '3) Запросы на услуги'},
        ),
    ]
