# Generated by Django 5.0.1 on 2024-01-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_alter_banner_options_alter_banneradd_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneradd',
            name='settings',
        ),
        migrations.DeleteModel(
            name='Faqs',
        ),
        migrations.RemoveField(
            model_name='lookbookadd',
            name='settings',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerAdd',
        ),
        migrations.DeleteModel(
            name='LookBook',
        ),
        migrations.DeleteModel(
            name='LookBookAdd',
        ),
    ]
