# Generated by Django 5.0.1 on 2024-01-10 09:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='letter',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='2) Описание комментария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_descriptions',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='1) Описнаие новости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='threats',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='3) Описание киберугроз'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='threats_descriptions',
            field=models.CharField(default=1, max_length=255, verbose_name='4) Описание threats'),
            preserve_default=False,
        ),
    ]
