# Generated by Django 5.0.1 on 2024-01-10 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0012_news_conclution_news_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='threats_descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='4) Описание threats'),
        ),
    ]
