# Generated by Django 5.0.1 on 2024-01-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0013_alter_news_threats_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions1', models.TextField(verbose_name='Описание')),
                ('name2', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions2', models.TextField(verbose_name='Описание')),
                ('name3', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions3', models.TextField(verbose_name='Описание')),
                ('name4', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions4', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Удобная Функция',
                'verbose_name_plural': 'Удобные Функции',
            },
        ),
    ]
