# Generated by Django 5.0.1 on 2024-01-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0014_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='descriptions1',
            field=models.TextField(verbose_name='Описание1'),
        ),
        migrations.AlterField(
            model_name='function',
            name='descriptions2',
            field=models.TextField(verbose_name='Описание2'),
        ),
        migrations.AlterField(
            model_name='function',
            name='descriptions3',
            field=models.TextField(verbose_name='Описание3'),
        ),
        migrations.AlterField(
            model_name='function',
            name='descriptions4',
            field=models.TextField(verbose_name='Описание4'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name1',
            field=models.CharField(max_length=255, verbose_name='Название1'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name2',
            field=models.CharField(max_length=255, verbose_name='Название2'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name3',
            field=models.CharField(max_length=255, verbose_name='Название3'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name4',
            field=models.CharField(max_length=255, verbose_name='Название4'),
        ),
    ]
