# Generated by Django 5.0.1 on 2024-01-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0015_alter_function_descriptions1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопросы')),
                ('answer', models.TextField(verbose_name='Ответы')),
            ],
            options={
                'verbose_name': '4) Частый вопрос',
                'verbose_name_plural': '4) Частые вопросы',
            },
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': '3) Удобная Функция', 'verbose_name_plural': '3) Удобные Функции'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '2) Новость', 'verbose_name_plural': '2) Новости'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '1) Слайд', 'verbose_name_plural': '1) Слайды'},
        ),
    ]
