# Generated by Django 5.0.1 on 2024-01-11 07:29

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0016_faq_alter_function_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='partner_image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': '5) Партнер',
                'verbose_name_plural': '5) Партнеры',
            },
        ),
    ]
