# Generated by Django 5.0.1 on 2024-01-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0017_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
