# Generated by Django 5.0.1 on 2024-01-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_partners_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='title',
        ),
    ]
