# Generated by Django 5.0.1 on 2024-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0022_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.AddField(
            model_name='faq',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Вопросы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='Ответы'),
        ),
    ]
