# Generated by Django 5.0.1 on 2024-01-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0023_remove_faq_answer_faq_name_alter_faq_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='comments',
            field=models.ManyToManyField(related_name='faq_comments', to='secondary.question', verbose_name='Комментарии к FAQ'),
        ),
    ]
