# Generated by Django 5.0.1 on 2024-01-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0024_remove_faq_name_remove_faq_question_faq_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='comments',
            new_name='comment',
        ),
    ]
