# Generated by Django 5.0.1 on 2024-01-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0025_rename_comments_faq_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='comment',
            new_name='comments',
        ),
    ]
