# Generated by Django 5.0.1 on 2024-01-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0026_rename_comment_faq_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '6) Вопрос', 'verbose_name_plural': '6) Вопросы'},
        ),
    ]
