# Generated by Django 5.0.1 on 2024-01-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_blog_options_alter_sale_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='devizadd',
            name='settings',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Devis',
        ),
        migrations.DeleteModel(
            name='DevizAdd',
        ),
    ]
