# Generated by Django 5.0.1 on 2024-01-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_blog_remove_devizadd_settings_delete_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp номер'),
        ),
    ]
