# Generated by Django 5.0.1 on 2024-01-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_about_title_alter_about_descriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddField(
            model_name='settings',
            name='descriptions_about',
            field=models.TextField(blank=True, null=True, verbose_name='Информационный текст о нас'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='whatsapp',
            field=models.URLField(default=1, verbose_name='Whatspp URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='whatsapp_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Whatsapp номер'),
            preserve_default=False,
        ),
    ]
