# Generated by Django 5.0.1 on 2024-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('why_1', models.CharField(max_length=100, verbose_name='Почему_1')),
                ('why_2', models.CharField(max_length=100, verbose_name='Почему_2')),
                ('why_3', models.CharField(max_length=100, verbose_name='Почему_3')),
            ],
            options={
                'verbose_name': 'Почему мы',
                'verbose_name_plural': 'Почему мы',
            },
        ),
    ]
