# Generated by Django 5.0.1 on 2024-01-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_why'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '2) Наша услуга', 'verbose_name_plural': '2) Наши услуги'},
        ),
        migrations.AlterModelOptions(
            name='why',
            options={'verbose_name': '3) Почему мы', 'verbose_name_plural': '3) Почему мы'},
        ),
    ]
