# Generated by Django 5.0.1 on 2024-01-11 08:08

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_service_options_alter_why_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='team_image/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('work', models.CharField(max_length=255, verbose_name='Должность')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('facebook', models.EmailField(max_length=254, verbose_name='facebook URL')),
                ('twitter', models.EmailField(max_length=254, verbose_name='twitter URL')),
                ('instagram', models.EmailField(max_length=254, verbose_name='instagram URL')),
                ('youtube', models.EmailField(max_length=254, verbose_name='youtube URL')),
            ],
            options={
                'verbose_name': '4) Команда',
                'verbose_name_plural': '4) Команды',
            },
        ),
    ]
