# Generated by Django 5.0.1 on 2024-01-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(verbose_name='facebook URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(verbose_name='instagram URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(verbose_name='twitter URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='youtube',
            field=models.URLField(verbose_name='youtube URL'),
        ),
    ]
