# Generated by Django 5.0.1 on 2024-01-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_team_email_team_experiences_team_language_team_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='experiences',
            new_name='experience',
        ),
    ]
