# Generated by Django 5.0.1 on 2024-01-12 05:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сам отзыв'),
        ),
    ]
