# Generated by Django 5.0.1 on 2024-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='why',
            name='why_4',
            field=models.CharField(default=1, max_length=100, verbose_name='Почему_3'),
            preserve_default=False,
        ),
    ]
