# Generated by Django 5.0.1 on 2024-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_why_why_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_url', models.URLField(verbose_name='Видео URL')),
            ],
            options={
                'verbose_name': '6) Видео',
                'verbose_name_plural': '6) Видео',
            },
        ),
        migrations.AlterField(
            model_name='why',
            name='why_4',
            field=models.CharField(max_length=100, verbose_name='Почему_4'),
        ),
    ]
