# Generated by Django 5.0.1 on 2024-01-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_chooseus_delete_why'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chooseus',
            name='why_2',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='why_3',
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='why_1',
            field=models.CharField(max_length=100, verbose_name='объяснение на почему мы'),
        ),
    ]
