# Generated by Django 5.0.1 on 2024-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_chooseus_why_2_remove_chooseus_why_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseus',
            name='why_2',
            field=models.CharField(default=1, max_length=100, verbose_name='Почему_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chooseus',
            name='why_3',
            field=models.CharField(default=1, max_length=100, verbose_name='Почему_3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='why_1',
            field=models.CharField(max_length=100, verbose_name='Почему_1'),
        ),
    ]
