# Generated by Django 5.0.1 on 2024-01-18 04:22

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_chooseus_why_2_chooseus_why_3_alter_chooseus_why_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
