# Generated by Django 5.0.1 on 2024-01-18 10:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.URLField(default=1, verbose_name='видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
