# Generated by Django 5.0.1 on 2024-01-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_about_remove_settings_descriptions_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '7) О нас', 'verbose_name_plural': '7) О нас'},
        ),
    ]
