# Generated by Django 5.0.1 on 2024-01-18 10:49

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_about2/', verbose_name='Фотография'),
        ),
    ]
