# Generated by Django 5.0.1 on 2024-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_service_video_alter_service_descriptions'),
        ('base', '0045_about_image2'),
    ]

    operations = [
    ]
